services:
  fnvw-build-backend:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: fnvw-build-backend:latest
    volumes:
      - ./target/:/app/target/
      - ./src/:/app/src/
